runtime: java11
instance_class: F1
automatic_scaling:
  max_instances: 3
  min_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
entrypoint: 'java -jar YOUR_ARTIFACT_NAME.jar'
